spring.application.name=spring-api
server.port=${SERVER_PORT:8080}

# Perfil ativo padrao (ativa 'local' para desenvolvimento na sua maquina)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Configuracao Base do Banco de Dados (Producao / Nuvem sobrescreve via variaveis de ambiente)
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
